### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by wasdee** [dunovank/jupyter-themes#170]
os: kali kde lastest version

[log]
pip install --upgrade jupyterthemes                                                           10:22:14
Collecting jupyterthemes
  Downloading jupyterthemes-0.17.3-py2.py3-none-any.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 314kB/s 
Collecting ipython<6.0 (from jupyterthemes)
  Downloading ipython-5.4.1-py3-none-any.whl (757kB)
    100% |████████████████████████████████| 757kB 1.6MB/s 
Requirement already up-to-date: matplotlib in ./anaconda/lib/python3.6/site-packages (from jupyterthemes)
Collecting lesscpy (from jupyterthemes)
  Downloading lesscpy-0.12.0-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 6.6MB/s 
Requirement already up-to-date: jupyter-core in ./anaconda/lib/python3.6/site-packages (from jupyterthemes)
Requirement already up-to-date: decorator in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Requirement already up-to-date: pickleshare in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Requirement already up-to-date: traitlets>=4.2 in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Requirement already up-to-date: pygments in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Collecting setuptools>=18.5 (from ipython<6.0->jupyterthemes)
  Downloading setuptools-36.3.0-py2.py3-none-any.whl (477kB)
    100% |████████████████████████████████| 481kB 1.8MB/s 
Requirement already up-to-date: pexpect; sys_platform != "win32" in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Requirement already up-to-date: simplegeneric>0.8 in ./anaconda/lib/python3.6/site-packages (from ipython<6.0->jupyterthemes)
Collecting numpy>=1.7.1 (from matplotlib->jupyterthemes)
  Downloading numpy-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 115kB/s 
Requirement already up-to-date: six>=1.10 in ./anaconda/lib/python3.6/site-packages (from matplotlib->jupyterthemes)
Requirement already up-to-date: python-dateutil in ./anaconda/lib/python3.6/site-packages (from matplotlib->jupyterthemes)
Requirement already up-to-date: pytz in ./anaconda/lib/python3.6/site-packages (from matplotlib->jupyterthemes)
Requirement already up-to-date: cycler>=0.10 in ./anaconda/lib/python3.6/site-packages (from matplotlib->jupyterthemes)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda/lib/python3.6/site-packages (from matplotlib->jupyterthemes)
Requirement already up-to-date: ply in ./anaconda/lib/python3.6/site-packages (from lesscpy->jupyterthemes)
Requirement already up-to-date: wcwidth in ./anaconda/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython<6.0->jupyterthemes)
Installing collected packages: setuptools, ipython, lesscpy, jupyterthemes, numpy
  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0
  Found existing installation: ipython 6.1.0
    DEPRECATION: Uninstalling a distutils installed project (ipython) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling ipython-6.1.0:
      Successfully uninstalled ipython-6.1.0
  Found existing installation: numpy 1.11.2
    Uninstalling numpy-1.11.2:
      Successfully uninstalled numpy-1.11.2
Successfully installed ipython-5.4.1 jupyterthemes-0.17.3 lesscpy-0.12.0 numpy-1.13.1 setuptools-36.3.0
Traceback (most recent call last):
  File "/home/kali/anaconda/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/kali/anaconda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg'

**Comment by dunovank** [comment]
hmm.... strange. Can you try installing/upgrading again (latest release is v0.17.6).

```
pip install --upgrade jupyterthemes
```

Not sure what the issue is here.
