### ISSUE TITLE
ImportError: No module named 'lesscpy'

### ISSUE THREAD

**Issue by victcity** [dunovank/jupyter-themes#173]
(TF13CPU) C:\Users\zh-2>jt -h
Traceback (most recent call last):
  File "d:\program files\anaconda3\envs\tf13cpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda3\envs\tf13cpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\TF13CPU\Scripts\jt.exe\__main__.py", line 5, in <module>
  File "d:\program files\anaconda3\envs\tf13cpu\lib\site-packages\jupyterthemes\__init__.py", line 5, in <module>
    from . import stylefx
  File "d:\program files\anaconda3\envs\tf13cpu\lib\site-packages\jupyterthemes\stylefx.py", line 3, in <module>
    import lesscpy
ImportError: No module named 'lesscpy'

**Comment by cardosan** [comment]
Got the same issue after having been able to solve issue #171

**Comment by dunovank** [comment]
rats... ok I'll try to update with a fix later today.

**Comment by dunovank** [comment]
Can someone check to see if this is fixed in the latest release (v0.17.7)?

**Comment by cardosan** [comment]
I wanted to try but experienced again #171 and messed up the enviro (interrupted when pip tried to update setuptools) :(
maybe builiding also a conda package would solve the prob...
```sh
$ conda list
# packages in environment at /home/giuseppec/miniconda3/envs/new:
#
altair                    1.2.0                    py36_0    conda-forge
appdirs                   1.4.3                    py36_0    conda-forge
arrow                     0.10.0                   py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
asteval                   0.9.8                    py36_0    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
brightway2                2.1.1                      py_1    cmutel
bw2analyzer               0.9.4                      py_0    cmutel
bw2calc                   1.6.2                      py_0    cmutel
bw2data                   2.4.6                      py_0    cmutel
bw2io                     0.5.10                     py_0    cmutel
bw2parameters             0.5.3                      py_3    cmutel
bw2speedups               2.2                       <pip>
ca-certificates           2017.7.27.1                   0    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
cryptography              1.9                      py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
docopt                    0.6.2                    py36_0    conda-forge
eight                     0.3.3                      py_0    haasad
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.1                         0    conda-forge
fasteners                 0.14.1                   py36_2    conda-forge
flask                     0.12.2                   py36_0    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
future                    0.16.0                   py36_0    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                         0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipyparallel               6.0.2                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.0.0                    py36_1    conda-forge
itsdangerous              0.24                     py36_1    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
jupyterthemes             0.17.8                    <pip>
lesscpy                   0.12.0                   py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
libxslt                   1.1.29                        5    conda-forge
lxml                      3.8.0                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
mkl                       2017.0.3                      0  
mkl-service               1.1.2                    py36_3  
monotonic                 1.3                      py36_0    conda-forge
nbconvert                 5.2.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py36_2    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numexpr                   2.6.2               np113py36_0    conda-forge
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0    conda-forge
palettable                3.0.0                    py36_0    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
pandas-datareader         0.5.0                    py36_0    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
patsy                     0.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
peewee                    2.10.1                   py36_0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
ply                       3.10                     py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.2.2                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyopenssl                 17.2.0                   py36_0    conda-forge
pypardiso                 0.2.2                      py_0    haasad
pyparsing                 2.2.0                    py36_0    conda-forge
pyprind                   2.10.0                   py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.2                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qgrid                     0.3.3                    py36_0  
qt                        5.6.2                         3    conda-forge
qtconsole                 4.3.1                    py36_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
requests-file             1.4.1                    py36_0  
requests-ftp              0.3.1                    py36_0    conda-forge
scipy                     0.19.1              np113py36_0  
seaborn                   0.8.0                    py36_0    conda-forge
setuptools                36.3.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
stats-arrays              0.4.2                     <pip>
stats_arrays              0.4.2                      py_0    cmutel
statsmodels               0.8.0               np113py36_0    conda-forge
terminado                 0.6                      py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
udatetime                 0.0.13                    <pip>
unicodecsv                0.14.1                   py36_0    conda-forge
unidecode                 0.04.21                  py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
vega                      0.4.4                    py36_1    conda-forge
voluptuous                0.10.5                   py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
werkzeug                  0.12.2                   py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
whoosh                    2.7.4                    py36_0    conda-forge
widgetsnbextension        3.0.2                    py36_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xlrd                      1.0.0                    py36_1    conda-forge
xlsxwriter                0.9.8                    py36_0    conda-forge
xlwt                      1.2.0                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge

```
