### ISSUE TITLE
error in install

### ISSUE THREAD

**Issue by kite8** [dunovank/jupyter-themes#181]
I had installed the jupyter-themes before in anaconda.
But I removed the anaconda environment once. remove all the packages, include the jupyter-notebook.
But when I create the new environment, the themes efforts still, but I want to change the themes.
So, I decide to install the jupyter-themes again. but I have trouble.

> (E:\ProgramData\Anaconda3) C:\Users\kite>pip install jupyterthemes
> Collecting jupyterthemes
>   Using cached jupyterthemes-0.17.8-py2.py3-none-any.whl
> Requirement already satisfied: ipython>=5.4.1 in e:\programdata\anaconda3\lib\si
> te-packages (from jupyterthemes)
> Requirement already satisfied: matplotlib>=1.4.3 in e:\programdata\anaconda3\lib
> \site-packages (from jupyterthemes)
> Requirement already satisfied: jupyter-core in e:\programdata\anaconda3\lib\site
> -packages (from jupyterthemes)
> Collecting lesscpy>=0.12.0 (from jupyterthemes)
>   Using cached lesscpy-0.12.0-py2.py3-none-any.whl
> Requirement already satisfied: decorator in e:\programdata\anaconda3\lib\site-pa
> ckages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: setuptools>=18.5 in e:\programdata\anaconda3\lib\
> site-packages\setuptools-27.2.0-py3.6.egg (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: pickleshare in e:\programdata\anaconda3\lib\site-
> packages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: simplegeneric>0.8 in e:\programdata\anaconda3\lib
> \site-packages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in e:\programdata\an
> aconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: traitlets>=4.2 in e:\programdata\anaconda3\lib\si
> te-packages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: jedi>=0.10 in e:\programdata\anaconda3\lib\site-p
> ackages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: colorama; sys_platform == "win32" in e:\programda
> ta\anaconda3\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: pygments in e:\programdata\anaconda3\lib\site-pac
> kages (from ipython>=5.4.1->jupyterthemes)
> Requirement already satisfied: numpy>=1.7.1 in e:\programdata\anaconda3\lib\site
> -packages (from matplotlib>=1.4.3->jupyterthemes)

> Exception:
> Traceback (most recent call last):
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\basecommand.py", line 215
> , in main
>     status = self.run(options, args)
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\commands\install.py", lin
> e 335, in run
>     wb.build(autobuilding=True)
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\wheel.py", line 749, in b
> uild
>     self.requirement_set.prepare_files(self.finder)
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380
> , in prepare_files
>     ignore_dependencies=self.ignore_dependencies))
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\req\req_set.py", line 666
> , in _prepare_file
>     check_dist_requires_python(dist)
>   File "E:\ProgramData\Anaconda3\lib\site-packages\pip\utils\packaging.py", line
>  48, in check_dist_requires_python
>     feed_parser.feed(metadata)
>   File "E:\ProgramData\Anaconda3\lib\email\feedparser.py", line 175, in feed
>     self._input.push(data)
>   File "E:\ProgramData\Anaconda3\lib\email\feedparser.py", line 103, in push
>     self._partial.write(data)
> TypeError: string argument expected, got 'NoneType'

I use the commad : pip install jupyterthemes
and : pip install --upgrade jupyterthemes
the same error

**Comment by kite8** [comment]
I have searched the 'jupyterthemes' folder in my anaconda, but nothing.
I had uesd the 'jt' command, it doesn't work.
pip uninstall jupyterthemes,  it display 
'Cannot uninstall requirement jupyterthemes, not installed'

**Comment by dunovank** [comment]
Hmm... I'm not sure. What version of python are you running?

**Comment by kite8** [comment]
@dunovank  My version of python is 3.6, I can install in my company computer, the same version of python  
as my home computer.

**Comment by yunyu-Mr** [comment]
I have the same problem.
Python 3.6.2
conda 4.3.24
jupyter 4.3.0

**Comment by sugs01** [comment]
Please update pip to the lasted version and then install jupyterthemes. The problem will be resolved.
