### ISSUE TITLE
install error ,need help

### ISSUE THREAD

**Issue by glados17** [dunovank/jupyter-themes#187]
jupyter-themes was running perfect on my computer,but after I uninstalled and reinstalled the anaconda,I found the jupyter-themes is still on before I installed it.  I want to change a themes so I run jt,but it shows no such a command ,then I try to install the jupyter-themes,and a error below came:

(D:\anaconda25) d:\1>pip install jupyterthemes
Collecting jupyterthemes
  Using cached jupyterthemes-0.18.2-py2.py3-none-any.whl
Collecting lesscpy>=0.12.0 (from jupyterthemes)
  Using cached lesscpy-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: matplotlib>=1.4.3 in d:\anaconda25\lib\site-packages (from jupyterthemes)
Requirement already satisfied: jupyter-core in d:\anaconda25\lib\site-packages (from jupyterthemes)
Collecting ipython>=5.4.1 (from jupyterthemes)
  Using cached ipython-5.5.0-py2-none-any.whl
Requirement already satisfied: six in d:\anaconda25\lib\site-packages (from lesscpy>=0.12.0->jupyterthemes)
Requirement already satisfied: ply in d:\anaconda25\lib\site-packages (from lesscpy>=0.12.0->jupyterthemes)
Requirement already satisfied: numpy>=1.7.1 in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: python-dateutil in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: functools32 in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: pytz in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: cycler>=0.10 in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in d:\anaconda25\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in d:\anaconda25\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already satisfied: decorator in d:\anaconda25\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already satisfied: setuptools>=18.5 in d:\anaconda25\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Exception:
Traceback (most recent call last):
  File "D:\anaconda25\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\anaconda25\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "D:\anaconda25\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\anaconda25\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\anaconda25\lib\site-packages\pip\req\req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "D:\anaconda25\lib\site-packages\pip\utils\packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "D:\anaconda25\lib\email\feedparser.py", line 177, in feed
    self._input.push(data)
  File "D:\anaconda25\lib\email\feedparser.py", line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'

So would anyone help me to check it? many thanks!

**Comment by glados17** [comment]
ok ，finally I uninstalled the anaconda and clean the cache and all the temp files on my win10，then I reinstalled the anaconda ，everything is cool now～～
