### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'C:\\Users\\xxx/.ipython/profile_default/static/custom/theme.css'

### ISSUE THREAD

**Issue by eromoe** [dunovank/jupyter-themes#19]
```
C:\Users\xxx\Desktop>jupyter-theme -T -t oceans16
Enabling toolbar
Traceback (most recent call last):
  File "D:\Python27\Scripts\jupyter-theme-script.py", line 9, in <module>
    load_entry_point('jupyter-themes==0.1', 'console_scripts', 'jupyter-theme')()
  File "d:\python27\lib\site-packages\jupyterthemes\__init__.py", line 154, in main
    install_theme(args.theme, profile=args.profile, toolbar=args.toolbar, fontsize=str(args.fontsize), update_properties
=update)
  File "d:\python27\lib\site-packages\jupyterthemes\__init__.py", line 77, in install_theme
    shutil.copy(source_path, themecss_path)
  File "d:\python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "d:\python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\xxx/.ipython/profile_default/static/custom/theme.css'
```
I think because `profile_default` don't have child folder.
Need create `static/custom/` first.

**Comment by dunovank** [comment]
I've made some changes to the install code so it's possible this issue is resolved if you're still interested. If so, would you mind posting an update here with your results?
