### ISSUE TITLE
failure to set theme

### ISSUE THREAD

**Issue by IgorDouven** [dunovank/jupyter-themes#208]
Successfully upgraded pip, installed jupyterthemes, but get following error message:

igor$ jt -t grade3
Traceback (most recent call last):
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 400, in reset_default
    delete_font_files()
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 94, in delete_font_files
    for fontfile in os.listdir(jupyter_custom_fonts):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/igor/.jupyter/custom/fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/igor/anaconda/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 58, in install_theme
    stylefx.reset_default(False)
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 402, in reset_default
    check_directories()
  File "/Users/igor/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 49, in check_directories
    os.makedirs(jupyter_custom)
  File "/Users/igor/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/igor/.jupyter/custom'

Am I doing something wrong?

**Comment by IgorDouven** [comment]
I ran the command with sudo and it worked. Not sure why that was required.
