### ISSUE TITLE
Can't apply themes on windows10

### ISSUE THREAD

**Issue by LinChenchuan** [dunovank/jupyter-themes#217]
**Hello! Dunovank!**
It can't works.
I would ask how it can be solve, 
else how can I solve decode problem like this. 
>UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence

**Thank you!**

Environment: python 3.6.4 64bit

> C:\Users\Shiling>jt -t chesterish
Traceback (most recent call last):
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shiling\AppData\Local\Programs\Python\Python36\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\__init__.py", line 98, in install_theme
    nbname=nbname)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\stylefx.py", line 291, in style_layout
    style_less += notebook.read() + '\n'
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence

**Comment by mlx809593812** [comment]
how can I solve decode problem like this.

UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence

**Comment by aiqu** [comment]
Try this(#216)

**Comment by mlx809593812** [comment]
@LinChenchuan,hello,how was your problem?

**Comment by LinChenchuan** [comment]
@mlx809593812 Hello, I have not solve the problem yet.
But, there is another case may help you: when I open a Chinese txt, it also show the  'gbk' error, after I search, open it and plus 'encoding=UTF-8' , it works. 
Here are codes:
> filename = "untitled.txt"
   with open(filename, encoding="utf-8) as f:
         mytext = f.read()

The case shows in python 3.6. In python 2.7, I open Chinese txt without problem.

May it help you~

**Comment by mlx809593812** [comment]
Thank you!I would have a try

**Comment by LinChenchuan** [comment]
@mlx809593812 Right now， I apply it in python 2.7 environment，it works! So I think it's some encoding problem in python 3.6.

**Comment by LinChenchuan** [comment]
@aiqu Thank you!

**Comment by aiqu** [comment]
@LinChenchuan 
As you said, it is default encode setting problem.
If you haven't solve it yet, check #218

**Comment by LinChenchuan** [comment]
@aiqu I change my system language from Chinese(PRC) to English(US), it works! without gbk error, on python 3.6! Thank you!

**Comment by LinChenchuan** [comment]
@aiqu I change system language from Chinese(PRC) to English(US), It works on python 3.6 without gbk error. Thank you!

**Comment by WMT123** [comment]
@aiqu 
 Hello, I have not solve the problem:

`PS G:\Python\Python2.7.14\Scripts> jt -r
Traceback (most recent call last):
  File "g:\python\python2.7.14\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "g:\python\python2.7.14\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "G:\Python\Python2.7.14\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "g:\python\python2.7.14\lib\site-packages\jupyterthemes\__init__.py", line 269, in main
    stylefx.reset_default(verbose=True)
  File "g:\python\python2.7.14\lib\site-packages\jupyterthemes\stylefx.py", line 431, in reset_default
    custom = '{0}{1}{2}.css'.format(fpath, os.sep, 'custom')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-11: ordinal not in range(128)`

I would appreciate it if you could give me some advice. Thanks!

**Comment by aiqu** [comment]
Could you put this right after the import statement in 'g:\python\python2.7.14\lib\site-packages\jupyterthemes\stylefx.py'?
```
reload(sys)
sys.setdefaultencoding('utf-8')
```

Before going any further, I'd like to know whether it is encoding problem.
And, could you show which value passed to fpath variable? If it is the encoding problem, I think os.sep and custom won't be the problem, so fpath is the most suspicious one.

**Comment by WMT123** [comment]
@aiqu 
It works! Thank you very much for your prompt reply!
The fpath variable contains Chinese.

**Comment by aiqu** [comment]
@WMT123 
Great! 👍

**Comment by dunovank** [comment]
Sorry for the delay on this. @rightx2 submitted a pull request to fix this issue which is included in the latest version (v0.18.4). If anyone finds the error persists after upgrading please follow up on this issue thread. Thanks!

**Comment by LinChenchuan** [comment]
@dunovank 
Thank you!!!

**Comment by LinChenchuan** [comment]
@dunovank 
Sorry... after I upgrading v0.18.4, it still returns "gbk" error.
I think the problem may be my system language is Chinese(PRC) and it's default code is "gbk".
as I reply to aiqu on 6 Jan
>@aiqu I change my system language from Chinese(PRC) to English(US), It works on python 3.6 without gbk error. Thank you!

I can't set default encode as utf-8 in python3.

Here are the Traceback.

>C:\Users\Shiling>jt -t oceans16
Traceback (most recent call last):
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shiling\AppData\Local\Programs\Python\Python36\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\__init__.py", line 101, in install_theme
    style_css = stylefx.less_to_css(style_less)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\jupyterthemes\stylefx.py", line 63, in less_to_css
    style_css = lesscpy.compile(tempfile)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\lesscpy\__init__.py", line 18, in compile
    p.parse(file=file)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\lesscpy\lessc\parser.py", line 154, in parse
    file, lexer=self.lex, debug=debuglevel)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\ply\yacc.py", line 1024, in parseopt_notrack
    lexer.input(input)
  File "c:\users\shiling\appdata\local\programs\python\python36\lib\site-packages\lesscpy\lessc\lexer.py", line 475, in input
    self.lexer.input(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 44258: illegal multibyte sequence

Thank you very much!
Solving problem is also a great process!
Much of Thanks!

**Comment by rightx2** [comment]
@dunovank  @LinChenchuan Forgot to say an important thing. Actually I changed the one line of code in `lesscpy/lessc/lexer.py `, too. (add `encoding='utf8'` and `errors='ignore'`.  I think I have to send pull request to that repository, too

**Comment by rightx2** [comment]
@dunovank  @LinChenchuan  I sent a pull request [lesscpy](https://github.com/lesscpy/lesscpy/pull/95) : https://github.com/lesscpy/lesscpy/pull/95. Sorry for missing infos. Thanks

**Comment by LinChenchuan** [comment]
@rightx2 @dunovank
Great!!! It works!!! Thank you very much!!! 
It is such a great exprience as solving problem with excellent programmers like you!!!
Thanks!!!
