### ISSUE TITLE
Issue with lesscpy/compilation. Unable to use any jt command.

### ISSUE THREAD

**Issue by sawarniayush** [dunovank/jupyter-themes#225]
I am using jupyter themes on Anaconda3 on Ubuntu 17.10.
I ge an unknown variables error when I use any jt command. I tried reinstalling upgrading everything. Please help.
`jt -t grade3 -cellw 88% -ofs 8.5 -nfs 10 -tfs 10 `

```
`Traceback (most recent call last):
  File "/home/ayush/anaconda3/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/home/ayush/anaconda3/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "/home/ayush/anaconda3/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 101, in install_theme
    style_css = stylefx.less_to_css(style_less)
  File "/home/ayush/anaconda3/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 63, in less_to_css
    style_css = lesscpy.compile(tempfile)
  File "/home/ayush/.local/lib/python3.6/site-packages/lesscpy/__init__.py", line 18, in compile
    p.parse(file=file)
  File "/home/ayush/.local/lib/python3.6/site-packages/lesscpy/lessc/parser.py", line 157, in parse
    self.register.close()
  File "/home/ayush/.local/lib/python3.6/site-packages/lesscpy/lessc/parser.py", line 44, in __close__
    raise CompilationError("\n".join(self.errors))
lesscpy.exceptions.CompilationError: E: (stream) line: 24, Syntax Error, token: 'css_class', '.'
E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @panel-bg

E: line: 0: Unknown variable @panel-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @edgeColor

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @button-color

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @selected-fg-bright

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-third

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @button-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @selected-tenth

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cell-width

E: line: 0: Unknown variable @cell-width

E: line: 0: Unknown variable @cell-width

E: line: 0: Unknown variable @cell-width

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @selected-fg-bright

E: line: 0: Unknown variable @nb-header-fg

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @button-color

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @nb-header-fg

E: line: 0: Unknown variable @dropdown-border

E: line: 0: Unknown variable @dropdown-border

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @selected-half

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @button-color

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @button-hover

E: line: 0: Unknown variable @button-focus-fg

E: line: 0: Unknown variable @button-focus-fg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @button-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @item-red

E: line: 0: Unknown variable @item-red

E: line: 0: Unknown variable @unemphasize-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @button-hover-bg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-hover-bg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @panel-header-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @modal-bg

E: line: 0: Unknown variable @modal-bg

E: line: 0: Unknown variable @alert-info-bg

E: line: 0: Unknown variable @panel-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @form-input-bg

E: line: 0: Unknown variable @button-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @dropdown-border

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @scroll-trough

E: line: 0: Unknown variable @scroll-trough

E: line: 0: Unknown variable @scrollbar

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @cc-border-selected

E: line: 0: Unknown variable @cc-border-edit

E: line: 0: Unknown variable @cc-border-edit

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @cc-border-edit

E: line: 0: Unknown variable @cc-border-selected

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @tc-border-edit

E: line: 0: Unknown variable @tc-border-edit

E: line: 0: Unknown variable @prompt-text

E: line: 0: Unknown variable @cc-prompt-bg

E: line: 0: Unknown variable @prompt-border

E: line: 0: Unknown variable @cc-output-bg

E: line: 0: Unknown variable @output-font-size

E: line: 0: Unknown variable @output-font-size

E: line: 0: Unknown variable @output-font-size

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @cc-output-bg

E: line: 0: Unknown variable @cc-output-bg

E: line: 0: Unknown variable @box-shadow

E: line: 0: Unknown variable @tc-border-edit

E: line: 0: Unknown variable @tc-border-edit

E: line: 0: Unknown variable @text-cell-fg

E: line: 0: Unknown variable @text-cell-bg

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @tc-border-selected

E: line: 0: Unknown variable @tc-border-edit

E: line: 0: Unknown variable @tc-prompt-fontsize

E: line: 0: Unknown variable @tc-prompt-fontsize

E: line: 0: Unknown variable @tc-prompt-border

E: line: 0: Unknown variable @tc-border-selected

E: line: 0: Unknown variable @text-cell-bg

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @text-cell-fg

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @prompt-line

E: line: 0: Unknown variable @header-fg

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @code-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @header-fg

E: line: 0: Unknown variable @header-fg

E: line: 0: Unknown variable @dropdown-hover

E: line: 0: Unknown variable @table-color

E: line: 0: Unknown variable @df-header-bg

E: line: 0: Unknown variable @table-bg

E: line: 0: Unknown variable @table-bg

E: line: 0: Unknown variable @table-bg

E: line: 0: Unknown variable @table-bg

E: line: 0: Unknown variable @cc-output-bg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @cc-output-fg

E: line: 0: Unknown variable @table-border

E: line: 0: Unknown variable @item-danger

E: line: 0: Unknown variable @item-info

E: line: 0: Unknown variable @item-warning

E: line: 0: Unknown variable @item-success

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @md-header-link

E: line: 0: Unknown variable @nb-name-hover

E: line: 0: Unknown variable @cm-link

E: line: 0: Unknown variable @item-blue

E: line: 0: Unknown variable @selected-third

E: line: 0: Unknown variable @selected-fg-bright

E: line: 0: Unknown variable @text-cell-fg

E: line: 0: Unknown variable @divider

E: line: 0: Unknown variable @unemphasize-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @dropdown-border

E: line: 0: Unknown variable @dropdown-border

E: line: 0: Unknown variable @panel-bg

E: line: 0: Unknown variable @item-danger

E: line: 0: Unknown variable @text-cell-bg

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @item-red

E: line: 0: Unknown variable @item-red

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @button-bg

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @button-panel-hover

E: line: 0: Unknown variable @button-bg

E: line: 0: Unknown variable @selected-half

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @selected-half

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @cmd-palette-form

E: line: 0: Unknown variable @cmd-palette-form

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @cmd-palette-form

E: line: 0: Unknown variable @cmd-palette-hover

E: line: 0: Unknown variable @button-panel-bg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @notebook-fg

E: line: 0: Unknown variable @selected-fg

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @disabled

E: line: 0: Unknown variable @cmd-palette-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @cc-border-selected

E: line: 0: Unknown variable @item-red

E: line: 0: Unknown variable @item-green

E: line: 0: Unknown variable @selected-third

E: line: 0: Unknown variable @codeblock-bg

E: line: 0: Unknown variable @panel-header-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cm-gutters

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @cm-attribute

E: line: 0: Unknown variable @cm-keyword

E: line: 0: Unknown variable @cm-builtin

E: line: 0: Unknown variable @cm-number

E: line: 0: Unknown variable @cm-string

E: line: 0: Unknown variable @cm-property

E: line: 0: Unknown variable @cm-def

E: line: 0: Unknown variable @cm-link

E: line: 0: Unknown variable @cm-string

E: line: 0: Unknown variable @cm-builtin

E: line: 0: Unknown variable @cm-property

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @divider

E: line: 0: Unknown variable @button-color

E: line: 0: Unknown variable @button-color

E: line: 0: Unknown variable @notebook-bg

E: line: 0: Unknown variable @cc-input-fg

E: line: 0: Unknown variable @item-theme

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @ansiblack

E: line: 0: Unknown variable @ansiblue

E: line: 0: Unknown variable @ansigray

E: line: 0: Unknown variable @ansigreen

E: line: 0: Unknown variable @ansigray

E: line: 0: Unknown variable @ansipurple

E: line: 0: Unknown variable @ansipurple

E: line: 0: Unknown variable @ansiyellow

E: line: 0: Unknown variable @ansired

E: line: 0: Unknown variable @stderr-bg

E: line: 0: Unknown variable @stderr-fg

E: line: 0: Unknown variable @js-error

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-line-height

E: line: 0: Unknown variable @cc-input-bg

E: line: 0: Unknown variable @cm-selected

E: line: 0: Unknown variable @cm-gutters

E: line: 0: Unknown variable @cm-gutters

E: line: 0: Unknown variable @cm-linenumber

E: line: 0: Unknown variable @cm-linenumber

E: line: 0: Unknown variable @cursor-info

E: line: 0: Unknown variable @cm-comment

E: line: 0: Unknown variable @cm-atom

E: line: 0: Unknown variable @cm-number

E: line: 0: Unknown variable @cm-variable

E: line: 0: Unknown variable @cm-variable

E: line: 0: Unknown variable @cm-keyword

E: line: 0: Unknown variable @cm-string

E: line: 0: Unknown variable @cm-meta

E: line: 0: Unknown variable @cm-operator

E: line: 0: Unknown variable @cm-builtin

E: line: 0: Unknown variable @cm-variable

E: line: 0: Unknown variable @cm-variable2

E: line: 0: Unknown variable @cm-variable3

E: line: 0: Unknown variable @cm-def

E: line: 0: Unknown variable @cm-error

E: line: 0: Unknown variable @cm-tag

E: line: 0: Unknown variable @cm-link

E: line: 0: Unknown variable @cm-storage

E: line: 0: Unknown variable @cm-entity

E: line: 0: Unknown variable @cm-string

E: line: 0: Unknown variable @selected-fg-bright

E: line: 0: Unknown variable @selected-fg-bright

E: line: 0: Unknown variable @cm-operator

E: line: 0: Unknown variable @header-fg

E: line: 0: Unknown variable @text-cell-fg

E: line: 0: Unknown variable @cm-variable3

E: line: 0: Unknown variable @cm-comment

E: line: 0: Unknown variable @cm-latex

E: line: 0: Unknown variable @cm-builtin

E: line: 0: Unknown variable @cm-string

E: line: 0: Unknown variable @cm-keyword

E: line: 0: Unknown variable @cm-number

E: line: 0: Unknown variable @cm-atom

E: line: 0: Unknown variable @cm-link

E: line: 0: Unknown variable @cm-number

E: line: 0: Unknown variable @cm-def

E: line: 0: Unknown variable @cursor-info

E: line: 0: Unknown variable @cm-selected

E: line: 0: Unknown variable @cm-selected

E: line: 0: Unknown variable @mathfontsize

E: line: 0: Unknown variable @prompt-line

E: line: 0: Unknown variable @cc-input-bg
`
```

**Comment by dunovank** [comment]
You need to change 8.5 to 85. (half-size font steps are inferred to be the second digit if the number is greater than 25. Gotta read that README closely ;) (see [here](https://github.com/dunovank/jupyter-themes#command-line-examples).
