### ISSUE TITLE
JT does not manage unavailable fonts as advertised

### ISSUE THREAD

**Issue by boffi** [dunovank/jupyter-themes#249]
If I try to use a system font `jt` tells me first that the font is not available (why? (it's a rethorical question)), next it tells me that it's going to ignore ALL my font requests and instead it will use the default fonts but eventually it dies with the following backtrace
```
$ jt -t grade3 -T -f consolas

        One of the fonts you requested is not available
        Setting all fonts to default
Traceback (most recent call last):
  File "/home/boffi/lib/miniconda3/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/home/boffi/lib/miniconda3/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "/home/boffi/lib/miniconda3/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 79, in install_theme
    dfonts=dfonts)
  File "/home/boffi/lib/miniconda3/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 142, in set_font_properties
    monofont, monofpath = stored_font_dicts(monofont)
ValueError: not enough values to unpack (expected 2, got 0)

```
I installed `jupyterthemes` using `pip`, over a fresh Anaconda install.  If you need any other detail...

Thanks in advance ፨ g

**Comment by boffi** [comment]
May I respectfully ask, why cannot I specify a sytem font and I've just to rely on the collection that you provide?  If  I specify the wrong face name, nothing bad is gonna happen, the browsers will happily use the backup faces specified in the `custom.css` file.  In my opinion

**Comment by evnb** [comment]
It seems to not work with system fonts, only the fonts listed [here](https://github.com/dunovank/jupyter-themes#monospace-fonts-code-cells)
