### ISSUE TITLE
jt --theme should create destination directory

### ISSUE THREAD

**Issue by dribnet** [dunovank/jupyter-themes#25]
Great package. Hit one small speed bump getting it working - would be helpful to add a check to see that destination directory exists.

```bash
tom$ jt -t oceans16
Traceback (most recent call last):
  File "/Users/tom/anaconda/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/Users/tom/anaconda/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 129, in main
    install_theme(args.theme, toolbar=args.toolbar, fontsize=int(args.fontsize), font="'"+args.font+"'")
  File "/Users/tom/anaconda/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 41, in install_theme
    shutil.copy(source_path, customcss_path)
  File "/Users/tom/anaconda/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/Users/tom/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/tom/.jupyter/custom/custom.css'

tom$ mkdir -p /Users/tom/.jupyter/custom

tom$ jt -t oceans16
Installing oceans16 at /Users/tom/.jupyter/custom
```

**Comment by dunovank** [comment]
Ah sorry about that, and will do. I'll update later today. Thanks for feedback!

**Comment by dunovank** [comment]
Should be fixed now
