### ISSUE TITLE
Jupyterhub error after activating theme

### ISSUE THREAD

**Issue by sigurdurb** [dunovank/jupyter-themes#272]
Hi, I installed this on a virtual machine running Jupyter notebook v.5.6.0 and Jupyterhub 0.8.1
It only happens when I try to open a notebook, new or already created. 
Also weird that file explorer and everything else is just in default color scheme and doesn't seem to be affected.
Any idea why 'get_custom_frontend_exporters' is undefined in the template?
```
[I 2018-08-30 18:33:52.838 SingleUserNotebookApp log:122] 201 POST /user/sigurdb/api/contents (sigurdb@127.0.0.1) 46.94ms
[E 2018-08-30 18:33:52.895 SingleUserNotebookApp web:1621] Uncaught exception GET /user/sigurdb/notebooks/Untitled35.ipynb?kernel_name=python3 (127.0.
0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='GET', uri='/user/sigurdb/notebooks/Untitled35.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 2949, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/notebook/notebook/handlers.py", line 43, in get
        except web.HTTPError as e:
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/handlers.py", line 424, in render_template
        host = re.match(r'^(.*?)(:\d+)?$', self.request.host).group(1)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/conda/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "<template>", line 2, in top-level template code
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/opt/conda/lib/python3.6/site-packages/notebook/templates/notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}
    jinja2.exceptions.UndefinedError: 'get_custom_frontend_exporters' is undefined
[E 2018-08-30 18:33:52.899 SingleUserNotebookApp log:114] {
      "X-Forwarded-Host": "localhost:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "127.0.0.1",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Cookie": "user-sigurdb=2|1:0|10:1535653506|12:user-sigurdb|48:YjNkYTE3Y2QtNmQ1ZC00YTk4LWJiOWYtOTBmOGQyMzczYTY4|5fca8761c1f7fc73fb17540136ea79dfe59caa5445b500289c8b622701355dd9; _xsrf=2|d9780392|bd0c24f3f1be698cca0e9e63ce27f91f|1534512224",
      "Referer": "http://localhost:8000/user/sigurdb/tree",
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0",
      "Host": "localhost:8000"
    }
[E 2018-08-30 18:33:52.899 SingleUserNotebookApp log:122] 500 GET /user/sigurdb/notebooks/Untitled35.ipynb?kernel_name=python3 (sigurdb@127.0.0.1) 7.77ms

```

**Comment by sigurdurb** [comment]
So this issue is not because of jupyterthemes, somehow this issue happened after I upgraded the notebook from 5.4.1 to 5.6.0. conda installing v. 5.4.1 again seems to fix the issue with the notebook but I uninstalled jupyterthemes and having some environmental errors on the testserver so won't be able to test-install it again.
