### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by rsomani95** [dunovank/jupyter-themes#284]
Firstly, thank you for creating jupyter-themes... noble project.

After trying to re-enable jupyter themes after a while, the following error showed up:

My entry in terminal:
     `jt -t grade3`

Error:
```
Traceback (most recent call last):
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 459, in reset_default
    delete_font_files()
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 106, in delete_font_files
    os.remove(abspath)
PermissionError: [Errno 1] Operation not permitted: '/Users/rahulsomani/.jupyter/custom/fonts/cmu-mono'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rahulsomani/anaconda/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 314, in main
    dfonts=args.defaultfonts)
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 59, in install_theme
    stylefx.reset_default(False)
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 462, in reset_default
    delete_font_files()
  File "/Users/rahulsomani/anaconda/lib/python3.6/site-packages/jupyterthemes/stylefx.py", line 106, in delete_font_files
    os.remove(abspath)
PermissionError: [Errno 1] Operation not permitted: '/Users/rahulsomani/.jupyter/custom/fonts/cmu-mono'
```

I tried running the command again as `sudo jt -t grade3` but to no avail.

**Comment by staticor** [comment]
same issues,

`Traceback (most recent call last):
  File "/Users/steve/.pyenv/versions/2.7.13/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/Users/steve/.pyenv/versions/2.7.13/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 314, in main
    dfonts=args.defaultfonts)
  File "/Users/steve/.pyenv/versions/2.7.13/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 59, in install_theme
    stylefx.reset_default(False)
  File "/Users/steve/.pyenv/versions/2.7.13/lib/python2.7/site-packages/jupyterthemes/stylefx.py", line 462, in reset_default
    delete_font_files()
  File "/Users/steve/.pyenv/versions/2.7.13/lib/python2.7/site-packages/jupyterthemes/stylefx.py", line 106, in delete_font_files
    os.remove(abspath)
OSError: [Errno 1] Operation not permitted: '/Users/steve/.jupyter/custom/fonts/sf-text'
`


And I deleted the custom fonts, it worked. 


`rm -rf /Users/${USERNAME}/.jupyter/custom/fonts`

**Comment by rsomani95** [comment]
Thanks @staticor, that's helpful. What I've also found while trying to setup a custom theme is that instead of replacing the contents of the `.jupyter/custom/` folder, it's more stable to set a preset theme and then copy paste the `css` code into the `custom.css` file in the folder.
