### ISSUE TITLE
TypeError: %x format: an integer is required, not float

### ISSUE THREAD

**Issue by jwfu** [dunovank/jupyter-themes#34]
I'm getting the TypeError when trying to install oceans16.

Here is the full dump:
~~~shell
$ jt -t oceans16 -alt -fs 10 -cw 900
Installing oceans16 at /home/jwfu/.jupyter/custom/custom.css
Traceback (most recent call last):
  File "/home/jwfu/anaconda3/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 109, in main
    install_theme(args.theme, monofont=args.monofont, monosize=args.monosize, nbfontfam=args.nbfontfam, tcfontfam=args.tcfontfam, cellwidth=int(args.cellwidth),  lineheight=int(args.lineheight), altlayout=args.altlayout, toolbar=args.toolbar)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 78, in install_theme
    style_css += less_to_css(style_less)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 37, in less_to_css
    style_css = lesscpy.compile(tempfile)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/__init__.py", line 18, in compile
    p.parse(file=file)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/parser.py", line 156, in parse
    self.post_parse()
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/parser.py", line 168, in post_parse
    out.append(pu.parse(self.scope))
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/block.py", line 43, in parse
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/block.py", line 43, in <listcomp>
    inner = list(utility.flatten([p.parse(scope) for p in inner if p]))
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/property.py", line 39, in parse
    self.parsed = self.process(style, scope)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/node.py", line 49, in process
    for t in tokens]
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/node.py", line 49, in <listcomp>
    for t in tokens]
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/plib/call.py", line 58, in parse
    result = getattr(color, name)(*args)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/color.py", line 237, in lighten
    return self._ophsl(color, diff, 1, operator.add)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/color.py", line 428, in _ophsl
    return self._rgbatohex(color)
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/color.py", line 398, in _rgbatohex
    for h in rgba]
  File "/home/jwfu/anaconda3/lib/python3.5/site-packages/lesscpy/lessc/color.py", line 394, in <listcomp>
    return '#%s' % ''.join(["%02x" % v for v in
TypeError: %x format: an integer is required, not float

~~~

**Comment by jwfu** [comment]
oops, same as #28
