### ISSUE TITLE
Jupyter-Notebook startup failed

### ISSUE THREAD

**Issue by Ashinch** [dunovank/jupyter-themes#340]
Jupyter-Notebook startup failed after installing jupyter-themes for Jupyter-Notebook that comes with Anaconda.

`Traceback (most recent call last):
  File "/Users/ash/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/ash/anaconda3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/ash/anaconda3/lib/python3.6/site-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists`

**Comment by Ashinch** [comment]
MacOS 10.14.3
