### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by EntilZha** [dunovank/jupyter-themes#5]
I am trying to get this running on recently upgraded Jupyter running on OS X El Capitan. I run into an issue when installing themes, below is what I did.

```
$ pip install git+https://github.com/dunovank/jupyter-themes.git
Collecting git+https://github.com/dunovank/jupyter-themes.git
  Cloning https://github.com/dunovank/jupyter-themes.git to /var/folders/hm/zl8d4mkx6vn19xwvdgrgx79r0000gn/T/pip-W4cyJY-build
Requirement already satisfied (use --upgrade to upgrade): sh in /usr/local/lib/python2.7/site-packages (from jupyter-themes==0.1)
Installing collected packages: jupyter-themes
  Running setup.py install for jupyter-themes
Successfully installed jupyter-themes-0.1
$ jupyter-theme -J -T -t oceans16-bright
Installing oceans16-bright at /Users/pedro/.ipython/profile_default/static/custom
Enabling toolbar
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-theme", line 9, in <module>
    load_entry_point('jupyter-themes==0.1', 'console_scripts', 'jupyter-theme')()
  File "/usr/local/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 128, in main
    install_theme(args.theme, profile=args.profile, toolbar=args.toolbar, jupyter=args.jupyter)
  File "/usr/local/lib/python2.7/site-packages/jupyterthemes/__init__.py", line 76, in install_theme
    themefile.writelines(lines)
IOError: [Errno 9] Bad file descriptor
$ echo "Try to Install on pip3 this time just in case that matters"
$ pip3 install git+https://github.com/dunovank/jupyter-themes.git
Collecting git+https://github.com/dunovank/jupyter-themes.git
  Cloning https://github.com/dunovank/jupyter-themes.git to /var/folders/hm/zl8d4mkx6vn19xwvdgrgx79r0000gn/T/pip-692xdmoy-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/hm/zl8d4mkx6vn19xwvdgrgx79r0000gn/T/pip-692xdmoy-build/setup.py", line 5, in <module>
        from jupyterthemes import THEMES_PATH
      File "/private/var/folders/hm/zl8d4mkx6vn19xwvdgrgx79r0000gn/T/pip-692xdmoy-build/jupyterthemes/__init__.py", line 34
        print "Profile %s does not exist at %s" % (profile, actual_path)
                                              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/hm/zl8d4mkx6vn19xwvdgrgx79r0000gn/T/pip-692xdmoy-build
```

Seems like its probably something pretty simple that I don't know about

**Comment by dunovank** [comment]
Can you try re-running without the toolbar flag (leave out -T)?

**Comment by EntilZha** [comment]
Will do. I got around to this again and noticed that it did install, but there was no toolbar. Perhaps this is it. Will update here when I find out

**Comment by mfitzp** [comment]
This is a Python 3 error  `print("Profile %s does not exist at %s" % (profile, actual_path))` will fix it. The package won't install if pip is running on Python 3, e.g.

    U:\>pip install git+https://github.com/dunovank/jupyter-themes.git
    Collecting git+https://github.com/dunovank/jupyter-themes.git
      Cloning https://github.com/dunovank/jupyter-themes.git to c:\users\fitzp002\ap
    pdata\local\temp\pip-9zsrtrr4-build
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "C:\Users\Fitzp002\AppData\Local\Temp\pip-9zsrtrr4-build\setup.py", l
    ine 5, in <module>
            from jupyterthemes import THEMES_PATH
          File "C:\Users\Fitzp002\AppData\Local\Temp\pip-9zsrtrr4-build\jupytertheme
    s\__init__.py", line 35
            print "Profile %s does not exist at %s" % (profile, home_path)
                                                  ^
        SyntaxError: invalid syntax

**Comment by dunovank** [comment]
that doesn't seem to break it on python 2, can someone test the latest commit on python 3?

**Comment by ZetaHunter** [comment]
Getting similar issue.
```
[root:~]# cat /proc/version
Linux version 4.1.6-249 (build-bot@cloud.online.net) (gcc version 4.9.1 (Ubuntu/Linaro 4.9.1-10ubuntu2) ) #1 SMP Mon Aug 31 12:34:47 UTC 2015
[root:~]# pip -V
pip 7.1.2 from /usr/local/lib/python3.5/dist-packages (python 3.5)
[root:~]# pip install git+https://github.com/dunovank/jupyter-themes.git
Collecting git+https://github.com/dunovank/jupyter-themes.git
  Cloning https://github.com/dunovank/jupyter-themes.git to /tmp/pip-ay3t8rxa-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-ay3t8rxa-build/setup.py", line 5, in <module>
        from jupyterthemes import THEMES_PATH
      File "/tmp/pip-ay3t8rxa-build/jupyterthemes/__init__.py", line 39
        print "creating profile: %s" % profile
                                   ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ay3t8rxa-build
```

**Comment by dunovank** [comment]
@EntilZha this checks out on my machine, osx el capitan running python 2. Nice job dude!. I'm closing this out.
