### ISSUE TITLE
Unable to install jupyter themes

### ISSUE THREAD

**Issue by SrivastavaKshitij** [dunovank/jupyter-themes#91]
Hey There , I am trying to install themes on my mac with Python 3.5 . 
When i use the command : `jupyter-theme -t onedork`, it gives the following error

'Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/stylefx.py", line 303, in reset_default
    delete_font_files()
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/stylefx.py", line 96, in delete_font_files
    for fontfile in os.listdir(jupyter_custom_fonts):
NotADirectoryError: [Errno 20] Not a directory: '/Users/kshitijsrivastava/.jupyter/custom/fonts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/jupyter-theme", line 11, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 78, in main
    install_theme(args.theme, monofont=args.monofont, monosize=args.monosize, nbfont=args.nbfont, nbfontsize=args.nbfontsize, tcfont=args.tcfont, tcfontsize=args.tcfontsize, cellwidth=args.cellwidth, margins=args.margins, lineheight=int(args.lineheight), cursorwidth=args.cursorwidth, cursorcolor=args.cursorcolor, altlayout=args.altlayout, altprompt=args.altprompt, hideprompt=args.hideprompt, vimext=args.vimext, toolbar=args.toolbar, nbname=args.nbname)
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 32, in install_theme
    stylefx.reset_default(False)
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/stylefx.py", line 305, in reset_default
    check_directories()
  File "//anaconda/lib/python3.5/site-packages/jupyterthemes/stylefx.py", line 47, in check_directories
    os.makedirs(jupyter_custom)
  File "//anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/kshitijsrivastava/.jupyter/custom'`

**Comment by purplezigar** [comment]
You need to run `pip install jupyterthemes` then customize it by running `jt -t onedork`

**Comment by dunovank** [comment]
if you install the latest version of jupyter-themes (`pip install --upgrade jupyterthemes`) and try again, does this work?

**Comment by SrivastavaKshitij** [comment]
It doesnt work. but thanks anyways
